In [1]:
import tensorflow as tf
import numpy as np

# **DEFINING THE REQUIREMENTS**

In [ ]:
n_layers = 5
epoch = 6
w_input = [36,500,500,150,50]
w_output = [500,500,150,50,3]
b_input = [36,500,150,50,3]
b_output = [500,500,150,50,3]

W=[]
B=[]

# **CREATING MY NETWORK**

In [ ]:
def create_network(n_layers,W,B,w_input,w_output,b_input,b_output):
  for i in range(n_layers):
    # weight initialisation

    # Define matrix size
    n_in = w_input[i]
    n_out = w_output[i]

    # Calculate the range for Xavier initialization
    limit = np.sqrt(6) / np.sqrt(n_in + n_out)

    W.append(tf.random.uniform((n_in, n_out), minval=-limit, maxval=limit))

    # bias initialisation

    # Define matrix size
    n_in = b_input[i]
    n_out = b_output[i]

    # Calculate the range for Xavier initialization
    limit = np.sqrt(6) / np.sqrt(n_in + n_out)

    B.append(tf.random.uniform((1, n_out), minval=-limit, maxval=limit))

# **THE INPUT DEFINING SECTION**

In [ ]:
one = [ [0,0,1,1,0,0],
        [0,1,1,1,0,0],
        [0,0,1,1,0,0],
        [0,0,1,1,0,0],
        [0,0,1,1,0,0],
        [1,1,1,1,1,1]
      ]

two = [ [0,0,1,1,0,0],
        [0,1,0,0,1,0],
        [0,0,0,0,1,0],
        [0,0,0,1,0,0],
        [0,0,1,0,0,0],
        [0,1,1,1,1,1]
      ]

three = [ [1,1,1,1,1,0],
          [0,0,0,0,0,1],
          [0,0,0,1,1,0],
          [0,0,0,1,1,0],
          [0,0,0,0,0,1],
          [1,1,1,1,1,0]
        ]

actual_output = [1,0,0]

actual_input = [np.ravel(one)]

# **THE MAIN BLOCK**

In [ ]:
create_network(n_layers,W,B,w_input,w_output,b_input,b_output)

In [ ]:
output = []
send_input(actual_input,W,B,n_layers)

PAssed layer : 0
PAssed layer : 1
PAssed layer : 2
PAssed layer : 3
PAssed layer : 4


In [ ]:
learning_rate = 1
backward_pass(actual_output,output[n_layers-1],output,W,B,n_layers-1,learning_rate)

THE LAYER: 4 Moving to shape : (1, 50)
THE LAYER: 3 Moving to shape : (1, 150)
THE LAYER: 2 Moving to shape : (1, 500)
THE LAYER: 1 Moving to shape : (1, 500)


In [ ]:
pred_output = []
predit(actual_input,W,B,n_layers)

<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[0.82980364, 0.        , 0.08744906]])>

In [ ]:
for i in range(epoch):
  output = []
  send_input(actual_input,W,B,n_layers)
  learning_rate = 1
  backward_pass(actual_output,output[n_layers-1],output,W,B,n_layers-1,learning_rate)
  pred_output = []
  print(predit(actual_input,W,B,n_layers))

PAssed layer : 0
PAssed layer : 1
PAssed layer : 2
PAssed layer : 3
PAssed layer : 4
THE LAYER: 4 Moving to shape : (1, 50)
THE LAYER: 3 Moving to shape : (1, 150)
THE LAYER: 2 Moving to shape : (1, 500)
THE LAYER: 1 Moving to shape : (1, 500)
tf.Tensor([[0.63507037 0.         0.16127861]], shape=(1, 3), dtype=float64)
PAssed layer : 0
PAssed layer : 1
PAssed layer : 2
PAssed layer : 3
PAssed layer : 4
THE LAYER: 4 Moving to shape : (1, 50)
THE LAYER: 3 Moving to shape : (1, 150)
THE LAYER: 2 Moving to shape : (1, 500)
THE LAYER: 1 Moving to shape : (1, 500)
tf.Tensor([[0.70629744 0.         0.13274087]], shape=(1, 3), dtype=float64)
PAssed layer : 0
PAssed layer : 1
PAssed layer : 2
PAssed layer : 3
PAssed layer : 4
THE LAYER: 4 Moving to shape : (1, 50)
THE LAYER: 3 Moving to shape : (1, 150)
THE LAYER: 2 Moving to shape : (1, 500)
THE LAYER: 1 Moving to shape : (1, 500)
tf.Tensor([[0.75385871 0.         0.11521049]], shape=(1, 3), dtype=float64)
PAssed layer : 0
PAssed layer : 1
PAs

#**THE PASSES**

In [ ]:
def forward_pass(input,W,B,N):
  return tf.nn.relu(np.add(np.dot(input,W[N]),B[N]))

In [ ]:
def backward_pass(actual_output,pred_output,output,W,B,N,learning_rate):
  if N==0:
    return 0
  print("THE LAYER:",N,end=" ")
  error = np.subtract(actual_output,pred_output)
  gradient_decent = pred_output * (1 - pred_output)
  delta = error * gradient_decent * learning_rate
  B[N] = np.add(B[N],delta)
  W[N] = np.add(W[N],np.dot(tf.transpose(output[N-1]),delta))
  prev_actual_output = [[0 for x in range(len(output[N-1][0]))]]
  for i in range(len(delta[0])):
    temp = []
    for j in range(len(output[N-1][0])):
      temp.append(output[N-1][0][j] * (1-output[N-1][0][j]) * delta[0][i])
    prev_actual_output = np.add(prev_actual_output,temp)
  print("Moving to shape :",np.shape(prev_actual_output))
  backward_pass(prev_actual_output,output[N-1],output,W,B,N-1,learning_rate)

In [ ]:
def send_input(input,W,B,n_layers):
  for i in range(n_layers):
    if i==0:
      output.append(forward_pass(input,W,B,i))
    else:
      output.append(forward_pass(output[i-1],W,B,i))
    print("PAssed layer :",i)


#**DEBUGGER**

In [ ]:
print(output)
print("#######################################################################################")
print(W)
print("#######################################################################################")
print(B)
print("#######################################################################################")
print(actual_output)

[]
#######################################################################################
[]
#######################################################################################
[]
#######################################################################################
[1, 0, 0]


# **Prediction**

In [ ]:
def predit(input,W,B,n_layers):
  for i in range(n_layers):
    if i==0:
      pred_output.append(forward_pass(input,W,B,i))
    else:
      pred_output.append(forward_pass(pred_output[i-1],W,B,i))
  return pred_output[n_layers-1]