<a href="https://colab.research.google.com/github/Happday-bot/Neural_Networks/blob/main/Updated_classifynumbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import random

# **DEFINING THE REQUIREMENTS**

In [2]:
n_layers = 5
epoch = 6
w_input = [36,500,500,150,50]
w_output = [500,500,150,50,9]
b_input = [36,500,150,50,9]
b_output = [500,500,150,50,9]

W=[]
B=[]

# **CREATING MY NETWORK**

In [3]:
def create_network(n_layers,W,B,w_input,w_output,b_input,b_output):
  for i in range(n_layers):
    # weight initialisation

    # Define matrix size
    n_in = w_input[i]
    n_out = w_output[i]

    # Calculate the range for Xavier initialization
    limit = np.sqrt(6) / np.sqrt(n_in + n_out)

    W.append(tf.random.uniform((n_in, n_out), minval=-limit, maxval=limit))

    # bias initialisation

    # Define matrix size
    n_in = b_input[i]
    n_out = b_output[i]

    # Calculate the range for Xavier initialization
    limit = np.sqrt(6) / np.sqrt(n_in + n_out)

    B.append(tf.random.uniform((1, n_out), minval=-limit, maxval=limit))

# **THE INPUT DEFINING SECTION**

In [39]:
one = [ [0,0,1,1,0,0],
        [0,1,1,1,0,0],
        [0,0,1,1,0,0],
        [0,0,1,1,0,0],
        [0,0,1,1,0,0],
        [1,1,1,1,1,1]
      ]

two = [ [0,0,1,1,0,0],
        [0,1,0,0,1,0],
        [0,0,0,0,1,0],
        [0,0,0,1,0,0],
        [0,0,1,0,0,0],
        [0,1,1,1,1,1]
      ]

three = [ [1,1,1,1,1,0],
          [0,0,0,0,0,1],
          [0,0,0,1,1,0],
          [0,0,0,1,1,0],
          [0,0,0,0,0,1],
          [1,1,1,1,1,0]
        ]

four = [  [0,0,0,1,0,0],
          [0,0,1,1,0,0],
          [0,1,0,1,0,0],
          [1,1,1,1,1,0],
          [0,0,0,1,0,0],
          [0,0,0,1,0,0]
        ]

five = [  [1,1,1,1,1,1],
          [1,0,0,0,0,0],
          [1,1,1,1,0,0],
          [0,0,0,0,1,0],
          [0,0,0,0,1,0],
          [1,1,1,1,0,0]
        ]

six = [   [0,1,1,1,1,1],
          [1,0,0,0,0,0],
          [1,0,0,0,0,0],
          [1,1,1,1,1,0],
          [1,0,0,0,0,1],
          [0,1,1,1,1,0]
        ]

seven = [ [1,1,1,1,1,1],
          [1,0,0,0,1,0],
          [0,0,0,1,0,0],
          [0,0,1,0,0,0],
          [0,1,0,0,0,0],
          [1,0,0,0,0,0]
        ]

eight = [ [0,1,1,1,1,0],
          [1,0,0,0,0,1],
          [1,1,1,1,1,1],
          [1,1,1,1,1,1],
          [1,0,0,0,0,1],
          [0,1,1,1,1,0]
        ]

nine = [  [0,1,1,1,1,0],
          [1,0,0,0,0,1],
          [0,1,1,1,1,1],
          [0,0,0,0,0,1],
          [0,0,0,0,0,1],
          [0,1,1,1,1,0]
        ]

#actual_output = [1,0,0]

#actual_input = [np.ravel(one)]
test_input = [np.ravel(three)]

data = [{tuple(np.ravel(one)):(1,0,0,0,0,0,0,0,0)},{tuple(np.ravel(two)):[0,1,0,0,0,0,0,0,0]},{tuple(np.ravel(three)):[0,0,1,0,0,0,0,0,0]},{tuple(np.ravel(four)):[0,0,0,1,0,0,0,0,0]},{tuple(np.ravel(five)):[0,0,0,0,1,0,0,0,0]},{tuple(np.ravel(six)):[0,0,0,0,0,1,0,0,0]},{tuple(np.ravel(seven)):[0,0,0,0,0,0,1,0,0]},{tuple(np.ravel(eight)):[0,0,0,0,0,0,0,1,0]},{tuple(np.ravel(nine)):[0,0,0,0,0,0,0,0,1]}]


# **THE MAIN BLOCK**

In [5]:
create_network(n_layers,W,B,w_input,w_output,b_input,b_output)

In [ ]:
output = []
send_input(actual_input,W,B,n_layers)

PAssed layer : 0
PAssed layer : 1
PAssed layer : 2
PAssed layer : 3
PAssed layer : 4


In [ ]:
learning_rate = 1
backward_pass(actual_output,output[n_layers-1],output,W,B,n_layers-1,learning_rate)

THE LAYER: 4 Moving to shape : (1, 50)
THE LAYER: 3 Moving to shape : (1, 150)
THE LAYER: 2 Moving to shape : (1, 500)
THE LAYER: 1 Moving to shape : (1, 500)


In [ ]:
pred_output = []
predit(actual_input,W,B,n_layers)

<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[0.82980364, 0.        , 0.08744906]])>

In [ ]:
for i in range(epoch):
  output = []
  send_input(actual_input,W,B,n_layers)
  learning_rate = 1
  backward_pass(actual_output,output[n_layers-1],output,W,B,n_layers-1,learning_rate)
  pred_output = []
  print(predit(actual_input,W,B,n_layers))

PAssed layer : 0
PAssed layer : 1
PAssed layer : 2
PAssed layer : 3
PAssed layer : 4
THE LAYER: 4 Moving to shape : (1, 50)
THE LAYER: 3 Moving to shape : (1, 150)
THE LAYER: 2 Moving to shape : (1, 500)
THE LAYER: 1 Moving to shape : (1, 500)
tf.Tensor([[0.63507037 0.         0.16127861]], shape=(1, 3), dtype=float64)
PAssed layer : 0
PAssed layer : 1
PAssed layer : 2
PAssed layer : 3
PAssed layer : 4
THE LAYER: 4 Moving to shape : (1, 50)
THE LAYER: 3 Moving to shape : (1, 150)
THE LAYER: 2 Moving to shape : (1, 500)
THE LAYER: 1 Moving to shape : (1, 500)
tf.Tensor([[0.70629744 0.         0.13274087]], shape=(1, 3), dtype=float64)
PAssed layer : 0
PAssed layer : 1
PAssed layer : 2
PAssed layer : 3
PAssed layer : 4
THE LAYER: 4 Moving to shape : (1, 50)
THE LAYER: 3 Moving to shape : (1, 150)
THE LAYER: 2 Moving to shape : (1, 500)
THE LAYER: 1 Moving to shape : (1, 500)
tf.Tensor([[0.75385871 0.         0.11521049]], shape=(1, 3), dtype=float64)
PAssed layer : 0
PAssed layer : 1
PAs

In [42]:
def nn_forward(actual_input,W,B,n_layers):
  output = []
  send_input(actual_input,W,B,n_layers,output)
  return output
def nn_backward(W,B,n_layers,normalised_actual_output,normalised_output,learning_rate):
  learning_rate = 1
  backward_pass(normalised_actual_output,normalised_output[n_layers-1],normalised_output,W,B,n_layers-1,learning_rate)

#**THE PASSES**

In [7]:
def forward_pass(input,W,B,N):
  return tf.nn.relu(np.add(np.dot(input,W[N]),B[N]))

In [46]:
def backward_pass(actual_output,pred_output,output,W,B,N,learning_rate):
  if N==0:
    return 0
  error = np.subtract(actual_output,pred_output)
  gradient_decent = pred_output * (1 - pred_output)
  delta = error * gradient_decent * learning_rate
  B[N] = np.add(B[N],delta)
  W[N] = np.add(W[N],np.dot(tf.transpose(output[N-1]),delta))
  prev_actual_output = [[0 for x in range(len(output[N-1][0]))]]
  for i in range(len(delta[0])):
    temp = []
    for j in range(len(output[N-1][0])):
      temp.append(output[N-1][0][j] * (1-output[N-1][0][j]) * delta[0][i])
    prev_actual_output = np.add(prev_actual_output,temp)
  backward_pass(prev_actual_output,output[N-1],output,W,B,N-1,learning_rate)

In [47]:
def send_input(input,W,B,n_layers,output):
  for i in range(n_layers):
    if i==0:
      output.append(forward_pass(input,W,B,i))
    else:
      output.append(forward_pass(output[i-1],W,B,i))


In [49]:
def batch_spliter(data):
  batch_size = 3
  random.shuffle(data)
  div = len(data)//batch_size
  for i in range(div):
    batch = data[i*batch_size:(i+1)*batch_size]
    batch_output = []
    batch_actual_output = []
    for j in batch:
      for k in j:
        actual_input = np.array(k)
        batch_actual_output.append(np.array(j[k]))
        batch_output.append(nn_forward(actual_input,W,B,n_layers))
    batch_actual_output , batch_output = batch_avg_normaliser(batch_actual_output,batch_output)

    learning_rate = 1

    nn_backward(W,B,n_layers,batch_actual_output,batch_output,learning_rate)

In [30]:
def batch_avg_normaliser(actual,pred):
  temp_actual = actual[0]
  temp_pred = pred[0]
  for i in range(1, len(actual)):
    temp_actual = np.add(temp_actual,actual[i])

  for i in range(1, len(pred)):
    for j in range(len(pred[i])):
      temp_pred[j] = np.add(temp_pred[j],pred[i][j])
  actual = np.divide(temp_actual,len(actual))
  pred = []
  for i in range(len(temp_pred)):
    pred.append(np.divide(temp_pred[i],len(actual)))
  return actual,pred

# The final Neural Network NN

In [53]:
epoch = 1000
for i in range(epoch):
  print("EPOCH :",i+1)
  batch_spliter(data)
  print(predict(test_input,W,B,n_layers))

EPOCH : 1
tf.Tensor(
[[0.32691573 0.         0.31739015 0.         0.32588824 0.31639115
  0.         0.32017588 0.32055604]], shape=(1, 9), dtype=float64)
EPOCH : 2
tf.Tensor(
[[0.32770045 0.         0.31643127 0.         0.32641531 0.31579447
  0.         0.32003495 0.3198492 ]], shape=(1, 9), dtype=float64)
EPOCH : 3
tf.Tensor(
[[0.32873234 0.         0.31638907 0.         0.32571259 0.31474742
  0.         0.31967408 0.31912175]], shape=(1, 9), dtype=float64)
EPOCH : 4
tf.Tensor(
[[0.32969624 0.         0.31597978 0.         0.32377595 0.31605109
  0.         0.31967657 0.32033712]], shape=(1, 9), dtype=float64)
EPOCH : 5
tf.Tensor(
[[0.3292612  0.         0.31547652 0.         0.32254663 0.31430862
  0.         0.31922866 0.32133278]], shape=(1, 9), dtype=float64)
EPOCH : 6
tf.Tensor(
[[0.32855258 0.         0.31488367 0.         0.32398183 0.3134675
  0.         0.31798998 0.32149765]], shape=(1, 9), dtype=float64)
EPOCH : 7
tf.Tensor(
[[0.32707188 0.         0.31416065 0.       

#**DEBUGGER**

In [ ]:
print(output)
print("#######################################################################################")
print(W)
print("#######################################################################################")
print(B)
print("#######################################################################################")
print(actual_output)

[]
#######################################################################################
[]
#######################################################################################
[]
#######################################################################################
[1, 0, 0]


# **Prediction**

In [43]:
def predict(input,W,B,n_layers):
  pred_output = []
  for i in range(n_layers):
    if i==0:
      pred_output.append(forward_pass(input,W,B,i))
    else:
      pred_output.append(forward_pass(pred_output[i-1],W,B,i))
  return pred_output[n_layers-1]

In [57]:
from tqdm import tqdm
import time

def perform_task():
    # Simulate a process with loading
    for _ in tqdm(range(100), desc="Processing..."):
        time.sleep(0.5)  # Simulating work

# Call the function
perform_task()

Processing...: 100%|██████████| 100/100 [00:50<00:00,  1.99it/s]
